### ISSUE TITLE
Should check the block height for waiting the block confirming not only sleeping

### ISSUE THREAD

**Issue by loloicci** [line/lbm-sdk#152]
https://github.com/line/lbm-sdk/blob/c612d35fd754597a6cb1b41ed00ba0d2bdf82aca/x/auth/tx/service_test.go#L394

and

https://github.com/line/lbm-sdk/blob/c612d35fd754597a6cb1b41ed00ba0d2bdf82aca/x/auth/tx/service_test.go#L433

Waits for block confirm with only simple sleep.
It should be checked with block height info and retry if height is not changed. And this change enables to shorten the sleeping time.

**Comment by egonspace** [comment]
There is no particular problem, so close.
