### ISSUE TITLE
Open wasm query responses to public

### ISSUE THREAD

**Issue by whylee259** [line/lbm-sdk#168]
## Summary

The current query responses are in the `internal` path.
So the outside of `wasm` module cannot refer to the response data structures such as cli_test.

## Proposal

open wasm query responses to public

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by brew0722** [comment]
The internal path is removed in the PR below.
https://github.com/line/lbm-sdk/pull/249
