### ISSUE TITLE
Research sim app(sim test)

### ISSUE THREAD

**Issue by shiki-tak** [line/lbm-sdk#309]

**Comment by shiki-tak** [comment]
https://github.com/line/lfb-sdk/tree/main/simapp
https://github.com/line/lfb-sdk/tree/c1c71f11af03c10fb57ddf325c336f0a7abf3225/x/bank/simulation
https://github.com/line/lfb-sdk/blob/main/Makefile#L300-L307

**Comment by egonspace** [comment]
Can we close this?
