### ISSUE TITLE
Validator whitelist feature

### ISSUE THREAD

**Issue by egonspace** [line/lbm-sdk#384]
## Summary
For the composition of the consortium chain, a validator whitelist feature is required so that only authorized accounts can register the validator.

For this, two functions are required.
- [staking] Check whitelist while it does `CreateValidator`
- [gov] following 3 new proposals
  - `ProposalAddToValidatorWhitelist`
  - `ProposalDeleteFromValidatorWhitelist`
  - `ProposalDisableValidatorWhitelist`: If it passed, the whitelist is deleted. It is required for changing the chain to public.
  - `ProposalEnableValidatorWhitelist`

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by egonspace** [comment]
I think a query for viewing the validator whitelist should also be implemented.

**Comment by 0Tech** [comment]
I think we can use same proposal for `ProposalDisableValidatorWhitelist` and `ProposalEnableValidatorWhitelist` with a boolean flag (e.g. enable), so if it is `true` it enables the feature, otherwise, it disables the feature.

**Comment by egonspace** [comment]
> I think we can use same proposal for `ProposalDisableValidatorWhitelist` and `ProposalEnableValidatorWhitelist` with a boolean flag (e.g. enable), so if it is `true` it enables the feature, otherwise, it disables the feature. If my suggestion looks fine, we can go further, using same proposal for `ProposalAddToValidatorWhitelist` and `ProposalRemoveFromValidatorWhitelist`. We can name it `ProposalModifyValidatorWhitelist` and add operation enum which contains `add` and `remove`.

It's like a matter of choice. If the proposal type is various, one option can be reduced, and if the type is reduced, an option will be added. I think you can choose one that is easier to implement.
