### ISSUE TITLE
Register `simapp` docker image to docker hub

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#455]
## Summary

We need to register `simapp`, default lbm-sdk binary, to docker hub for sdk's testing and etc.

The public repository of docker hub is already ready. And the name is `line/lbm-simapp`.
https://hub.docker.com/r/line/lbm-simapp

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by NehaK275** [comment]
can i solve this? @zemyblue

**Comment by zemyblue** [comment]
> can i solve this? @zemyblue

@NehaK275, thank you for your interesting and support. But this task is partially related to #456 issue, so we want to assign this to @0Tech . Please take a look at lbm-sdk and if there are things that need to be corrected, please add issue or PR. Thank you very much.
