### ISSUE TITLE
class_id of token.EventIssue contains unnecessary characters

### ISSUE THREAD

**Issue by brew0722** [line/lbm-sdk#538]
## Summary of Bug

when I executed the `lbm tx token issue`, it will be returned below.
```
                {
                    "type": "lbm.token.v1.EventIssue",
                    "attributes": [
                        {
                            "key": "class_id",
                            "value": "\"678c146a\""
                        }
                    ]
```
If you look at the value, it contains \", which seems unnecessary.

## Version

e2acac9105ef61402a75ca7e376e6a906aa2e6b2

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by 0Tech** [comment]
Because `TypedEvent` may contain arbitrary structures, it uses json formated value. So you must unmarshal the value.

**Comment by zemyblue** [comment]
This is same issue with #463 .
