### ISSUE TITLE
Effectiveness of Address Format Change and Next Action

### ISSUE THREAD

**Issue by torao** [line/lbm-sdk#578]
## Summary

This task is to sort out useful features in order to reduce the differences between lbm-sdk and cosmos-sdk.

Report on how effective the address format changes in #298 has worked/is expected to work, and complete the work if we're reverting it back to the cosmos-sdk implementation. Expected results are:

* Report on the effects of lbm-sdk style implementations (e.g., performance measurements, design insights, considerations, etc.).
* Decision whether to keep the lbm-sdk implementation or revert to the cosmos-sdk implementation.
* If revert to a cosmos-sdk implementation, plan to complete that work.

Parent: #549
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by tnasu** [comment]
>Regarding the target function, the difference narrowed relatively if the number of executions was large. Also, since the target function is executed at least 69 times, there seems to be no big difference in execution time between lbm-sdk@v0.46.0-rc2 and cosmos-sdk@v0.45.1.

I agree with you. In my opinion, let's rollbacks these codes.

@torao How about you?

**Comment by zemyblue** [comment]
> > Regarding the target function, the difference narrowed relatively if the number of executions was large. Also, since the target function is executed at least 69 times, there seems to be no big difference in execution time between lbm-sdk@v0.46.0-rc2 and cosmos-sdk@v0.45.1.
> 
> I agree with you. In my opinion, let's rollbacks these codes.
> 
> @torao How about you?

I also agree @tnasu 's opinion.

**Comment by ulbqb** [comment]
Fixed the [result](https://github.com/line/lbm-sdk/issues/578#issuecomment-1174709683).

@tnasu @zemyblue 
I'm sorry, it seems that the latest results weren't reflected when you were commenting. But the result remains the same. there seems to be no big difference in execution time between lbm-sdk and cosmos-sdk.
