### ISSUE TITLE
Decide whether to import x/ibc from ibc-go and use it or update it.

### ISSUE THREAD

**Issue by shiki-tak** [line/lbm-sdk#585]
wasmd v0.27.0 uses v3 of ibc-go.
https://github.com/cosmos/ibc-go/blob/v3.0.0/modules/core/24-host/validate.go#L21

I added DefaultMaxPortCharacterLength becase the source related to ibc has not been update in our repository.

It is necessary to decide whether to import and use or update x/ibc before developing IBCs.

_Originally posted by @shiki-tak in https://github.com/line/lbm-sdk/pull/570#discussion_r915473509_

**Comment by zemyblue** [comment]
I think it's better to remove `x/ibc` module in this repo and import `ibc-go`.

**Comment by ulbqb** [comment]
I think it is difficult to import `ibc-go`. So I updated `x/ibc` simply.
