### ISSUE TITLE
Check the changes of cosmwasm/wasmd v0.29

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#684]
## Summary

Check the changed from cosmwasm/wasmd v0.27 to v0.29. 

## Problem Definition

The latest cosmwasm/wasmd version is v0.29.0-rc0 (https://github.com/CosmWasm/wasmd/releases/tag/v0.29.0-rc0) and our wasm is based cosmwasm/wasmd v0.27 (refer #570)
So we need to check the changes of v0.28 and v0.29. If the critical bug is fixed through these versions, we need to upgrade the base version.

### [Compatibility](https://github.com/CosmWasm/wasmd/tree/v0.29.0-rc0#compatibility)
<!DOCTYPE html>

asmd | wasmvm | cosmwasm-vm | cosmwasm-std
-- | -- | -- | --
0.29 | v1.1.0 |   | 1.0-1.1
0.28 | v1.0.0 |   | 1.0-1.1
0.27 | v1.0.0 |   | 1.0

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by da1suk8** [comment]
**Summarize**

v0.27.0 → v0.28.0, there were three fix changes.
- https://github.com/CosmWasm/wasmd/pull/917
- https://github.com/CosmWasm/wasmd/commit/2a9c5c1ea542d3d968bebeea7031a7d0a4e38ffa
- https://github.com/CosmWasm/wasmd/commit/288609255ad92dfe5c54eae572fe7d6010e712eb

v0.28.0 → v0.29.0, there were many changes. I put notable changes of CHANGELOG.

**Notable changes**
- BaseAccount and pruned vesting account types can be re-used for contracts addresses
- A new [MsgInstantiateContract2](https://github.com/CosmWasm/wasmd/pull/1014/files#diff-bf58b9da4b674719f07dd5421c532c1ead13a15f8896b59c1f724215d2064b73R75) was introduced which is an additional value for message type events
- Store event contains a new attribute with the code checksum now
- New wasmd tx wasm instantiate2 CLI command for predictable addresses on instantiation
- New cosmwasm_1_1 CosmWasm capability (former "feature") was introduced in [cosmwasm/#1356](https://github.com/CosmWasm/cosmwasm/pull/1356) to support total supply queries
- Protobuf files are published to [buf.build](https://buf.build/cosmwasm/wasmd/docs/main:cosmwasm.wasm.v1)
