### ISSUE TITLE
remove time-based upgrade

### ISSUE THREAD

**Issue by dudong2** [line/lbm-sdk#787]
## Summary
When a time based upgrade was performed in cosmos-sdk, there was a case where the node could not consensus normally. 
Cosmos-sdk merged pr aboue removing time based upgrade.
We need to reflect this.

ref: https://github.com/cosmos/cosmos-sdk/pull/8849

## Proposal

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by zemyblue** [comment]
Cosmos-sdk seems to have the same issue. 
So I think it's better to propose about removing time-based upgrade proto in cosmos-sdk, and if the proposal is approved and merged, then apply it. How about this?
