### ISSUE TITLE
Analysis and improve log management function.

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#825]
## Summary

Analysis and improve log management function

## Problem Definition
Current system just write the log in one file without any truncating. 
As a result, the log file is too large and difficult to copy and analyze.

## Proposal

* Investigate how to write the log to a file
* improve log managing function
  * Log level setting for each module
  * Set log file storage path
  * Set log file storage method (plain text, json or etc)
  * split log file
    * Truncate the log file at specific size intervals
    * Truncate the log file to specific hours or days
  * log file rotating
    * Keep only the set number of log files - delete old log files
  * add config setting
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by dudong2** [comment]
## lbm-sdk log system

Currently, lbm-sdk supports zerolog-based logging to stderr.
```go
func InterceptConfigsPreRunHandler(cmd *cobra.Command, customAppConfigTemplate string, customAppConfig interface{}) error {
	//...

	var logWriter io.Writer
	if strings.ToLower(serverCtx.Viper.GetString(flags.FlagLogFormat)) == ostcfg.LogFormatPlain {
		logWriter = zerolog.ConsoleWriter{
			Out:        os.Stderr,
			TimeFormat: "2006/01/02-15:04:05.999",
		}
	} else {
		logWriter = os.Stderr
	}

	logLvlStr := serverCtx.Viper.GetString(flags.FlagLogLevel)
	logLvl, err := zerolog.ParseLevel(logLvlStr)
	if err != nil {
		return fmt.Errorf("failed to parse log level (%s): %w", logLvlStr, err)
	}

	serverCtx.Logger = ZeroLogWrapper{zerolog.New(logWriter).Level(logLvl).With().Timestamp().Logger()}

	//...
}
```
However, log level support, which were previously supported, and log file creation by module are not supported. For better logging, log level support per module and log file creation function should be added.

## how to write the log to file

The current zerolog log system is based on io.Writer. io.Writer has several customizations, and zerolog supports all of them(ex. lumberjack, file-lotetelogs, ...).

```go
var zerologLogger zerolog.Logger
log_path := serverCtx.Viper.GetString(flags.FlagLogPath)
// initialize the rotator
logFile := log_path + "/app-%Y-%m-%d.%H:%M:%S.log"
rotator, err := rotatelogs.New(
	logFile,
	<rotation time>
	<max age or rotation count>
)
if err != nil {
	panic(err)
}
zerologLogger = zerolog.New(rotator).With().Timestamp().Logger()

zerologLogger.Info("test log")
```
