### ISSUE TITLE
Not supporting `MsgMultiSend` of x/bank

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#868]
## Summary

Disable `MsgMultiSend` of x/bank

## Problem Definition

When sending coin with `MsgMultiSend`, we can make sure that the source of the amount you are sending cannot be clearly identified. And `MsgMultiSend` can be replaced with `MultiMsg` txs. Cosmos-SDK is also trying to change to single signer at `cosmos/cosmos-sdk issues/12628`. So, it would be better to disable it for now and apply the changed function when it is stabilized later in Cosmos-SDK so that it can be used.

## Proposal

Let's return an error if use `MsgMultiSend` in the `x/bankplus`. And use `x/bankplus` instead of `x/bank` as default.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by scalalang2** [comment]
Hello ✋ @zemyblue. 
I'm here to begin contributing this project.
I have some experience with developing blockchain with cosmos-sdk.
If you haven't begun to fix this issue yet. I'd like to work on fixing this issue for my first journey into the `lbm-sdk` project
