### ISSUE TITLE
MsgModify in x/token,collection should also accept "uri"

### ISSUE THREAD

**Issue by 0Tech** [line/lbm-sdk#899]
## Summary

MsgModify accepts `base_img_uri` or `img_uri` for backward-compatibility. MsgModify should also accept `uri`, because the corresponding proto has been updated into `uri`.

## Problem Definition

The current implementation may confuse new users, so we should add a key `uri`.

## Proposal

1. Make `MsgModify` to accept a key `uri` for its changes.
2. Users must use either of `uri` or old key. If they use both of the key in the same time, the validation logic must emit an error.

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zemyblue** [comment]
If both `img_uri` and `uri`are exited in the same Msg, is it confused?
